### ISSUE TITLE
Selecting only IOS build in Xamarin archive config still it build android as well

### ISSUE THREAD

**Issue by dev-manishpandey** [bitrise-io/steps-repository-scanner#13]
I've selected IOS build config in Xamarin archive but still i'm seeing android build messages in log. This does not seems to be issue in msbuild where it only builds one if specified so.

**Comment by doomsayer13** [comment]
Hi @manish-rapidd,
Thanks for reporting, we will check it ASAP.

**Comment by godrei** [comment]
To successfully build your xamarin project first we call a build command against your solution file. If the solution's build command builds your android project as well, you did not disabled the android project in your solution properly. 

To properly disable a project:

- double click on your solution file in the project navigator
- select build/Configurations
- select Configuration Mappings
- select the Configuration and Platform you use on bitrise
- deselect the project in the project list
