### ISSUE TITLE
Can't complete initial set up process

### ISSUE THREAD

**Issue by aaronschubert0** [bitrise-io/steps-repository-scanner#4]
Currently trying to add my first repo to Bitrise but "Validating repository" step always fails because of repository-scanner@1.3.2 (exit code: 1)

Any way to get around this?

**Comment by viktorbenei** [comment]
Hi,

Can you please send us the logs in email, to letsconnect@bitrise.io ?
We'll have a look - we're already working on a fix for this step.

In the meantime you can follow this guide (section) on how you can skip the scanner, and provide the settings manually: http://devcenter.bitrise.io/v1.0/docs/custom-ios-app-setup#section-register-your-ios-app-using-the-manual-setup-method

The design in the guide is a bit outdated, but the point is to _not_ to select any branch, but just scroll down a bit and select the "configure manually" option, which will skip the scanner step.

**Comment by aaronschubert0** [comment]
@viktorbenei Awesome, I already chose to configure it manually, and managed to get started, so don't have the logs anymore unfortunately!

**Comment by viktorbenei** [comment]
No problem at all, we got logs from another user, we'll fix that issue. If you'd have an issue with this step in the future feel free to create a new issue & please send the logs to us in email ;)
